package Exceptions;

import java.io.IOException;

public class Throwsexception {

	public static void main(String[] args)  throws IOException,ArithmeticException{
		// TODO Auto-generated method stub
		
			throw new IOException("this is arithmetic exception");
			
	
		
//		catch(ArithmeticException e)
//		{
//			System.out.println(e.getMessage());
//		}
		
//		finally 
//		{
//			
//		}

	}

}
